prgrms-web-devcourse/Team-Tasty-Masiottae-FE

.babelrc
tsconfig.json

alias를 사용해 절대경로를 사용할 수 있게 해뒀습니다. 
- src/ + constants, hooks, utils, components를 @constants 처럼 사용하시면 됩니다.
- 현재 알려 주신 사이트 방법 2번쨰 next.config.json에 webpack 수정이 안되네요 
- 그래서 냅두고 나머지만 바꿨는데, 바벨 설정, next.config.json 설정 없이도 잘 동작하고 있네요

chore: 절대 경로 설정 alias

---

pages/main/index.tsx
src/components/PostCard.tsx

리뷰 반영중 Prop Name을 변경하지 않은 부분이 있어서 간단하게 수정 적용했습니다!

fix(MainPage): PropsName 오타 수정

---

.babelrc
package-lock.json
package.json
pages/_app.tsx
src/components/Layout/Header.tsx
src/components/Layout/Navigation.tsx
src/components/Layout/index.tsx
styles/globals.css
tsconfig.json

#7 
모바일에 최적화된 template 레이아웃 구현
- 모바일 친화적인 반응형 style : width를 500px로 잡고, 그 이하일 땐 media 쿼리로 width 100%를 줬습니다.
- 해당 css를 준 Container 안에 헤더와 하단 네비를 넣고
- Props로 페이지 컴포넌트를 받아서 헤더와 네비 사이에 오도록 합니다. 
- _app파일의 Component를 감싸 children으로 넘겨줍니다.
현재 아래 그림처럼 padding을 기본으로 준 상태기 때문에 width 100%로 주면 됩니다.

style: Layout 컴포넌트 마크업 완성

---

src/components/Input.tsx

기본 Input 컴포넌트 구현
- 기본적인 prop을 제외하고는 optional로 뒀습니다.
-  onChange, onBlur 이벤트 발생시 해당 함수가 호출됩니다. ( 존재할 때만 실행 )
- isValid false일시 border가 빨강으로 변합니다. (border 속성이 오버라이딩되지 않았다면)
- className 부여 : styled(Input)``을 사용하기 위해선 className을 부여해야 합니다.

feature: 기본 Input 컴포넌트 생성

---

pages/login/index.tsx
pages/myInfo/index.tsx
src/components/Layout/Header.tsx
src/components/Layout/Navigation.tsx
src/constants/pageUrl.ts

#14 
헤더, 네비의 link 기능을 구현했습니다. 
- 네비게이션, 헤더에 Link를 추가하고 pageUrl 을 연동했습니다.
- constants > pageUrl : pageUrl 을 상수화했습니다. 
- 버튼을 누르고 링크 이동 시 isactive가 true가 되고 color가 mainPink로 바뀝니다. ( 커스텀 속성을 줄 땐 소문자로만 쓰라고 해서 isactive로 바꿨습니다. ㅜ ) 
- 메뉴판, 내정보 페이지엔 로고 대신 페이지 Title이 헤더에 담깁니다.

faeture: 네비게이션 기능 구현

---

src/components/Button.tsx

버튼 컴포넌트 생성
- children, onClick 외엔 optional로 처리했습니다.
- styled(Button)`` 오버라이딩시 className을 부여하셔야 적용됩니다.
- hover, active, disabled: opacity: 0.7 적용

feature: Button 컴포넌트 생성

---

pages/myInfo/ChangeProfileModal.tsx
pages/myInfo/UserData.tsx
pages/myInfo/UserProfile.tsx
pages/myInfo/index.tsx
src/constants/theme.ts

#5 
- 내 정보 페이지 + 모달 이벤트 구현
- 마크업
- 닉네임, 프로필 클릭시 수정 모달 구현
- 모달은 계진님 것을 적용하려했으나 useClcikaway가 잘 먹히지 않았고, 전에 말하신 배경이 어두워지고, 화면 중앙에 나오는 기능이 아직 모달에 완성되지 않아 제가 만들었습니다. 
- 만약 3번 구현이 여의치 않다면 제 부분만 예외인 것 같으니 제가 만든 모달을 쓰면 될 것 같습니다.
https://user-images.githubusercontent.com/79133602/181449439-44687a9e-afce-416d-82dc-e04461abab39.mp4

feat: 내 정보 페이지 + 모달 이벤트 구현

---

pages/login/index.tsx
src/constants/inputConstant.ts

resolve #4 
- 로그인 마크업 작업 + 유효성 검사
- style 작업
- 유효성 검사 후 에러 메시지를 Input 하단에 출력 합니다.
- handler 로직 구축( 유효성 검사 통과시 api 호출을 하도록 작성했습니다.)
- validate는 따로 커스텀 훅으로 분리할 예정입니다.
- 비밀번호 미리보기도 utils에 분리할 예정입니다.

feature: 로그인 페이지 마크업 + 유효성 검사 구현

---

pages/login/index.tsx
src/components/Layout/Navigation.tsx
src/constants/inputConstant.ts

resolve #50 
하단 NavBar클릭 이벤트 감지 영역 확장
- Link 태그를 사용하는 데 해당 태그는 styled가 적용되지 않아서 내부 a 태그에 style을 줬습니다. 
- 이제 아이콘 뿐만 아니라 아래 파란색 부분 모두 감지합니다.

fix: 하단 NavBar클릭 이벤트 감지 영역 확장 

---

pages/index.tsx
pages/search/[category].tsx
pages/user/index.tsx
src/components/MenuCard.tsx

resolve #49
기존 앱 영역내에서만 스크롤 되던 부분들을 전부 전체 스크롤로 수정했습니다.

refactor: 메인, 검색, 유저 메뉴판 페이지 스크롤 영역 수정

---

src/lib/axios/index.ts
src/lib/axios/interceptors.ts
src/lib/axios/localToken.ts

resolve #52
- axios 인스턴스의 이름은 axiosInstance로 했습니다. 
- baseUrl은 process.env.REACT_APP_API_URL로 env 파일에 api url을 넣어서 사용합니다.
interceptor에 사용될 함수들을 작성했습니다.
- handleRequest: request.interceptor 에 사용되는 함수로 config가 undefined가 아니고 token이 있다면 header에 token을 집어넣습니다.
- 아직 refresh token이 어떻게 담겨 오는 지 확실히 몰라서  handleRequest에 refresh token 관련 코드는 작성하지 않았습니다. 
- api 완성 후 해당 사항을 refreshToken이라는 함수로 구현할 생각입니다. 
- 현재 header에 token이 담길 필요가 없는 요청인 경우도  interceptor에서 전부 token을 넣어줍니다.  api 요청시 직접 config로 넣을까 생각했는데, 이 방법이 더 깔끔해 보일 거 같아서 이렇게 했습니다.
- 혹시 불필요하게 header에 공간 차지를 하는 걸까요?
- commit msg 또 feature로 해버렸네요 ㅜ squash merge 할 땐 전부 지우고 feat 쓰겠습니다.

feat: axios create, interceptor 구현

---

src/components/Filter.tsx
src/components/Modal.tsx

#40 
검색 페이지에서 사용할 Filter 컴포넌트를 구현했습니다.
Modal 컴포넌트를 이용하여 구현하고, 모달이 열렸을 때 뒷 배경에 있는 상호작용을 막는 로직을 추가했습니다.

feat: Filter 컴포넌트 구현

---

tsconfig.json

tsconfig에 컴마 2개로 오류 때문에 컴파일이 되지 않습니다

fix: tsconfig 오류 제거

---

next.config.js
src/hooks/mutations/useChangeImageMutation.ts
src/hooks/mutations/useSignupMutation.ts
src/lib/axios/index.ts

chore: Next.config rewrites 추가

---

pages/edit-menu/[id].tsx
src/components/TagContainer.tsx

#62 
- max 값을 넘기면 태그가 들어가지 않습니다
- waring을 수정했습니다

Fix : 태그 컨테이너 warning 수정 및 max값 설정

---

next.config.js
src/lib/axios/index.ts

white label page 에러 수정
- next.config.js의 rewrite 함수 수정
- axios 인스턴스의 baseUrl 수정

fix: white label page 에러 수정

---

src/components/SearchForm.tsx

필터를 클릭시 Tag 리스트를 포함한 모달을 띄우도록 구현했습니다.
- 태그 클릭시 선택
- 검색 상태에 적용

feat: TagCotainer 모달 구현

---

src/hooks/queries/useCheckedValue.ts

resolve #99 
닉네임 중복 체크 hook 수정
- useCheckedValue hook의 axios.get 요청에 대한 response type을 명세에 따라 수정했습니다.

fix: 닉네임 중복 체크 hook 수정

---

src/hooks/mutations/useSignupMutation.ts

resolve #105
- 회원가입시 로그인 api 호출
- useSignupMutation onSuccess에 useLoginMutation mutate 사용

refactor: 회원가입시 자동으로 로그인 되도록 수정

---

pages/create-menu/index.tsx
src/components/ImageUploader.tsx
src/components/Layout/Header.tsx

resolve #119
- 피그마 대로 스타일 적용
- 이미지 업로더 컴포넌트 스타일을 변경했습니다.

style: 이미지 업로드 컴포넌트 스타일 적용

---

pages/index.tsx
src/components/MenuCard.tsx
src/components/MenuCardList.tsx

resolve #123
메뉴 카드 최종 디자인을 적용했습니다.

style: MenuCard 최종 디자인 적용

---

pages/signup/index.tsx

resolve #3 
회원가입 최종 디자인 적용
- Input, Button, Title, ImageUploader 스타일 변경
- 에러,성공 메시지 기본 컴포넌트 InputMessage로 교체

style: 회원가입 최종 디자인 적용

---

pages/myInfo/index.tsx
src/components/myInfo/UserData.tsx
src/components/myInfo/UserProfile.tsx

resolve #135
- 피그마 최종 디자인 적용
- input, button, Title, Text... 등 최종 디자인 대로 style 적용
- theme에 바뀐 색상 적용
- InputMessage 기본 컴포넌트 적요
- 불필요한 state 제거

style: 내정보 페이지 최종 디자인 적용

---

styles/globals.css

style: SUIT-Medium으로 폰트 변경

---

pages/login/index.tsx

resolve #139
- 최종 디자인 적용
- 로그인 api 에러 시 존재하지 않는 회원 에러 메시지 출력
- 회원가입 누르면 회원가입 페이지로 이동
- 로그인 에러 시 존재하지 않는 회원 에러 메시지 출력

style: 로그인 최종 디자인 적용

---

pages/myInfo/password.tsx

feat: 비밀번호 변경 api 연동

---

src/constants/token.ts
src/hooks/mutations/useLoginMutation.ts
src/utils/localToken.ts

token 타입 변경
로그인, 회원가입 시 받아오는 response data가 변경되서 해당 data에 맞게 token의 타입도 변경했습니다.

fix: token 타입 변경

---

src/recoil/currentUser.ts

currentUser 날라가는 문제만 해결
해당 페이지에서 새로고침시 hydration 에러가 발생합니다. 
`Error: Hydration failed because the initial UI does not match what was rendered on the server.`
위 에러는 서버에서 pre rendering한 react 트리와 클라이언트 단에서 만든 react 트리가 다르면 생기는 오류로 해결중인데 시간이 얼마나 걸릴지 몰라 일단 되는 것부터 push했습니다.
다른 페이지에서 새로고침 될 때는 괜찮습니다.

fix: currentUser 날라가는 문제만 해결

---

pages/index.tsx
pages/search/[category].tsx
pages/search/index.tsx
pages/user/[id].tsx
src/components/FranchiseInfo.tsx
src/components/FranchiseInfoList.tsx
src/components/MenuCard.tsx
src/components/MenuCardList.tsx
src/components/Modal.tsx
src/components/SkeletonCardList.tsx
src/components/SkeletonFranchiseList.tsx

resolve #203 
- 메뉴 카드와 프랜차이즈 정보에 스켈레톤 UI 를 적용했습니다.
- 기본 모달이 하단에 붙는 이슈가 있어서 transform 설정을 수정했습니다.
- 검색결과가 없을 시에 안내 문구를 추가했습니다.

feat: MenuCard, FranchiseInfo Skeleton UI 적용 

---

pages/user/[id].tsx
src/components/SearchForm.tsx
src/components/SkeletonFranchiseList.tsx
src/hooks/queries/useSearchMenuList.ts
src/hooks/queries/useSearchMyMenuList.ts
src/interfaces/index.ts

나만의 메뉴판 페이지에 좋아요한 메뉴 검색 기능을 추가했습니다.
- 작성한 메뉴, 좋아요한 메뉴 목록을 토글하면서 확인할 수 있습니다.
- 각 탭을 전환할때마다 검색 조건은 초기화됩니다.

feat: userPage 좋아요한 메뉴 api 적용

---

src/components/myInfo/UserProfile.tsx

- myInfo Image objectFit="cover"로 변경
- 닉네임 변경 아이콘 크기 줄이기
-  모달 위치 좀더 위에서 나오게 하기
제가 실험한 사진이 잘 나왔는데 릴리의 강아지 사진도 잘 나올지 모르겠습니다. 👀

style:  myinfo 리뷰 반영

---

src/components/Avatar.tsx
src/components/FilterForm.tsx
src/components/MenuCard.tsx
src/components/SkeletonCardList.tsx
src/components/Tag.tsx

- 메뉴카드 높이 고정
- 맛필터 태그 소형 디바이스에서도 3*3으로 나오도록 수정
- 필터 버튼 수정
- 메뉴카드 폰트 축소
- 기본 이미지 예외처리 추가

style: 검색 페이지 관련 스타일 수정

---

pages/index.tsx
pages/search/[category].tsx
pages/search/index.tsx
pages/user/[id].tsx
src/components/Input.tsx
src/components/MenuCard.tsx
src/components/SearchForm.tsx
src/components/SkeletonCardList.tsx
src/hooks/queries/useSearchMyMenuList.ts
src/interfaces/index.ts
src/utils/queryString.ts

- 사용자 메뉴판에서 유저 각각의 메뉴판을 보여줄 수 있도록 수정
- 기본 이미지 BIG_LOGO로 수정
- Skeleton UI 각 페이지별 적정 갯수 렌더링 하도록 수정
- form submit 발생 시 Input blur 되도록 수정

feat: 유저 메뉴판 페이지 유저별 API 적용

---

src/components/MenuCard.tsx
src/constants/image.ts

- 기존 이미지를 대체할 Default image 추가

refactor: 메뉴카드 기본 이미지 변경 후 적용

---

pages/detail/[id].tsx
src/components/Avatar.tsx
src/components/detail/CommentInput.tsx
src/components/detail/CommentList.tsx
src/components/detail/MenuDetail.tsx

resolve #194 
상세페이지 필요한 최종 부분 수정
- Title width 고정
- max-width 설정
- 태그 화면 넘침
- Tag를 감싸는 flex container에 flex-wrap: wrap;
- 옵션 / 댓글 글씨 크기 키우기
- 0.2rem씩 증가
- 메뉴 수정 라우팅
- router.push(`/edit-menu/${menu.id})`
- 메뉴 작성자 / 댓글 작성자 아바타나 이름 클릭 시 해당 사용자로 라우팅
- router.push(`/user/{userId})`

feat: 상세페이지 보완

---

pages/search/[category].tsx
pages/user/[id].tsx

style: 헤더와 fixed 요소 사이 공백 제거

---

src/components/Layout/Navigation.tsx

- navigation 아이콘 색 풀리는 것 해결
-  anchor 태그로 변환

fix: navigation 수정

---

src/components/Layout/index.tsx

style: 헤더 레이아웃 축소에 따른 레이아웃 스타일 수정
