pages/index.tsx, pages/search/[category].tsx, pages/search/index.tsx, src/components/MenuCard.tsx, src/components/PostCard.tsx, src/constants/cardData.ts
resolve #28
resolve #29 
피그마 시안대로 검색 페이지 마크업을 구현했습니다.
- 검색 Input 구현
- 카테고리 헤더 구현
- 정렬 select 구현
- 필터 선택 버튼 구현
MenuCard, InfiniteScroll은 MainPage에서 구현한 컴포넌트와 hook을 사용했습니다. (#9) / (#26)
=> feat: 검색 페이지 마크업 구현

src/components/Layout/Navigation.tsx
하단 Navigation의 속성명을 selected로 변경 후 타입을 boolean으로 변경
- isactive, active에서 non boolean에 boolean 타입을 줄 수 없다는 에러는 Icon에 이미 active, isactive 속성이 boolean이 아닌 상태로 존재했기 때문이었네요 ㅜ 
- selected로 바꾸니 타입 문제가 해결됐습니다.
=> refactor(Navigation): 아이콘 active 속성을 selected로 변경 및 타입 boolean으로 수정

pages/index.tsx, pages/search/[category].tsx, pages/user/index.tsx, src/components/MenuCardList.tsx, src/constants/cardData.ts, src/types/index.ts, tsconfig.json
resolve #67 
기존 페이지마다 `.map()`을 통해서 카드 리스트를 렌더링 하던 부분을 MenuCardList 컴포넌트로 분리했습니다.
Response 데이터와 일치하는 데이터를 받을 수 있도록 types에 menu, user, franchise interface를 작성했습니다.
=> feat: MenuCardList 구현

package-lock.json, package.json, pages/_app.tsx, src/interfaces/User.ts, src/interfaces/index.ts, src/recoil/currentUser.ts, tsconfig.json
resolve #53 
- recoil 설치 후 현재 인증한 사용자 정보를 atom으로 관리하도록 구현
> atom을 관리하는 폴더
현재 currentUser 파일에 인증한 사용자 정보를 atom으로 만들어 뒀습니다.  default는 테스트를 위해 더미를 넣어뒀습니다. 이후에 api를 호출할 수 있게 되면 수정하겠습니다.
useState와 유사합니다. 기본 값으로 atom을 가져와서 넣어주시면 됩니다.
현재 dummy currentUser의 image는 외부 소스입니다. Image 컴포넌트에 해당 소스를 넣으시려면 next.config.js파일에 다음과 같이 외부 소스 도메인을 입력해줘야 합니다.
=> feat: currentUser Recoil 구축

src/lib/axios/localToken.ts, tsconfig.json
#52 
- axiosInstance 사용시 window is not defined 에러 해결
- NEXT JS는 SSR 방식, 서버에선 window localStorage에 접근하지 못하기 때문에 발생한 오류
- token은 null이어도 axsios 자체의 에러가 나지 않습니다. 
- page가 loaded되고 window가 defined된 시점에 localStrorage에 접근하도록 조건문 추가 
- 전
- 후
=> fix: interceptor localToken 에러, window is not defined 해결

pages/index.tsx, pages/search/[category].tsx, pages/user/index.tsx, src/components/MenuCard.tsx, src/components/MenuCardList.tsx, src/hooks/queries/useMenuList.ts
resolve #83
메뉴 카드 리스트를 API를 통해 렌더링 적용했습니다.
- 중간 발표를 위해 우선 검색, 사용자 메뉴 등의 조건은 적용하지 않고 전체 메뉴만 조회하도록 되어 있습니다.
=> feat: Get MenuList API 적용

pages/detail/[id].tsx, src/components/detail/MenuDetail.tsx, src/hooks/mutations/useChangeImageMutation.ts, src/hooks/mutations/useChangeNickNameMutation.ts, src/hooks/mutations/useChangePasswordMutation.ts, src/hooks/mutations/useChangeSnsAccountMutation.ts, src/hooks/queries/useCommentList.ts, src/hooks/queries/useMenu.ts, src/hooks/queries/useMenuByUserId.ts, src/hooks/queries/useUser.ts, src/interfaces/index.ts
resolve #95 
메뉴 상세 페이지에 메뉴 단건 조회 API를 연동했습니다.
- useRouter hook을 이용해 동적인 id를 가져오고, 이를 통해 useMenu hook을 쏴서 얻은 data를 menu라는 이름으로 뿌립니다.
- optionList의 필드명이 내려오는대로 interface를 수정했습니다.
- Menu의 optionList 필드를 Omit을 통해 id를 빼도록 수정했습니다.
=> feat: 메뉴 상세 페이지 API 적용

pages/create-menu/index.tsx, pages/search/[category].tsx, pages/user/index.tsx, src/components/MenuCard.tsx, src/components/MenuCardList.tsx, src/components/SearchForm.tsx, src/constants/searchOption.ts
reslove #96
메뉴 리스트 순서를 임시로 reverse 해서 렌더링 하도록 구현했습니다.
추후 백엔드에서 정렬 옵션 API를 내려준 후 삭제 예정입니다.
=> refactor: MenuList 순서 Reverse

src/components/ImageUploader.tsx, src/lib/axios/index.ts
resolve #103 
- 정규식을 사용해서 jpg, png, jpeg 파일만 들어가게 했습니다.
- png 확장자를 넣었을 때 
- jfif 확장자를 넣었을 때
- (에러 메시지와 함께 화면이 바뀌지 않음)
=> feat: 이미지 업로더 형식 제한 추가

src/components/TagContainer.tsx, src/hooks/queries/useTasteList.ts
resolve #102 
- 이미지 컨테이너에 api를 붙였습니다
useTasteList 훅을 만들었습니다.
franchiseList와 같이 캐싱 infinity 처리 했습니다.
태그 컨테이너에 붙이고, 배경을 흰색으로 처리했습니다. 
db에 저장되어있는 결과값이 나옵니다.
=> feat: 태그 컨테이너 api로 교체

pages/detail/[id].tsx, src/components/detail/CommentInput.tsx, src/components/detail/CommentList.tsx, src/components/detail/MenuDetail.tsx, src/hooks/mutations/usePostCommentMutation.ts, src/hooks/queries/useCommentList.ts, src/interfaces/index.ts, src/utils/getDate.ts
#112 
제목:
메뉴 상세 페이지 댓글 API(comments) 적용
- 기능
- 댓글 조회(GET)
- 댓글 작성(POST)
- 날짜 추가(getDate 함수 작성)
- 디자인
- 기존 휴지통 아이콘을 ... 을 눌렀을 때 삭제 버튼이 뜨도록 수정했습니다.
- 날짜는 댓글 작성 닉네임 오른쪽에 배치했습니다.
=> feat: 메뉴 상세 페이지 댓글 API(comments) 적용, 디자인 개선

pages/login/index.tsx, src/hooks/mutations/useLoginMutation.ts
resolve #107
- useLoginMutation 구현 및 로그인 페이지 적용
로그인 페이지에서 모든 유효성 검사 통과 후 useLoginMutation 사용해 로그인 후 메인페이지로 이동하게 했습니다.
- 로그인 시 useLoginMutation 의 mutate가 onSuccess라면 토큰을 localStorage에 저장하고, user 정보를 받아 currentUser recoilState에 넣어줍니다.
=> feat: useLoginMutation 구현 및 로그인 페이지 적용

pages/create-menu/index.tsx, pages/edit-menu/[id].tsx, src/components/FranchiseSelect.tsx, src/components/ImageUploader.tsx, src/components/TagContainer.tsx, src/components/detail/MenuDetail.tsx, src/hooks/mutations/useChangeMenuMutation.ts, src/hooks/mutations/usePostMenuMutation.ts, src/hooks/queries/useFranchiseList.ts, src/hooks/queries/useTasteList.ts, src/interfaces/index.ts
resolve #109
- 프랜차이즈 api를 붙인 FranchiseSelect를 만들었습니다.
- Edit Page에 사용할 수정 mutaiton을 생성했습니다
- 프랜차이즈 api를 붙인 FranchiseSelect
Select 를 분리해서  컴포넌트 내에서 api를 불러오도록 했습니다.
따라서 props는 따로 받지 않고 onChange event Handler 만 받습니다. 
- Edit Page에 사용할 수정 mutaiton을 생성했습니다
edit Page 에 사용할 mutaition을 생성했습니다.
=> feat: 프랜차이즈 컴포넌트 분리 / EditPage mutiation 작성

pages/search/[category].tsx, pages/user/index.tsx, src/components/SearchForm.tsx, src/constants/searchOption.ts, src/hooks/queries/useSearchMyMenuList.ts, src/interfaces/index.ts, src/utils/queryString.ts
resolve #124 
검색 조건 (키워드, 정렬, 맛 태그)에 따른 검색기능을 추가했습니다.
현재 정해진 API 요청 방식대로 요청은 정상적으로 작동되나 서버측 문제로 
- 댓글기준 정렬
- 맛 태그 검색
기능은 정상 동작하지 않습니다.
영상 촬영을 진행하려 했는데 메뉴가 싹 비워져서 찍지 못하고 있습니다..
=> feat: 나만의 메뉴 페이지 검색 API적용

src/hooks/mutations/useLoginMutation.ts, src/hooks/mutations/useSignupMutation.ts
- 로그인 시 router.replace('/) 되도록 변경
- 현재 회원가입 시 user 정보가 오지 않아서 자동 로그인을 위해 회원가입 onSuccess시 로그인을 하도록 함, 
- 각 페이지에서 onSubmit시 router.replace하기 보다 useLoginMutaion onSuccess시 라우팅하는 게 적합하다고 판단
- 로그인 페이지에서 mutation error가 나면, `존재하지 않는 회원입니다.`를 출력할 예정
=> refactor: 로그인 시 router 되도록 변경

next.config.js
Image 컴포넌트 src 외부 리소스 에러 해결
현재  아래 도메인에서 이미지를 가져다 쓰고 있는데, Next js는 현재 도메인과 다른 곳의 리소스를 사용하면 에러가 난다고 합니다. 
- 'user-images.githubusercontent.com',
- 'masiottae-image-bucket.s3.ap-northeast-2.amazonaws.com'
그래서 next.config.js에 해당 도메인을 등록했습니다.
=> chore: Image 컴포넌트 src 외부 리소스 에러 해결

src/components/detail/CommentInput.tsx, src/components/detail/CommentList.tsx, src/components/detail/MenuDetail.tsx, src/utils/getDate.ts
resolve #133 
메뉴 상세 페이지 최종 디자인 적용
- 피그마에는 이미지와 그 아래 컨테이너가 화면에 꽉차도록 그려져있는데.. 기본 레이아웃 흐름에 맞춰서 좌우 padding을 갖고 있어서 해결이 안되어 패딩이 있는 상태로 적용했습니다.
- 맛 태그들은 일단 기존의 Tag 컴포넌트와 동작이 다른 것이 있어서 스타일을 유사하게 직접 만들어 넣어뒀습니다.
- Input을 4.8rem 혹은 5.6rem으로 설계해주셨는데, 위아래 padding 계산과 안의 content의 가운데 정렬이 힘들어 일단 4rem으로 만들었는데, 바꿔야할 것 같다면 의견 주시면 감사하겠습니다.
=> feat: 메뉴 상세 페이지 최종 디자인 적용

package-lock.json, package.json, pages/signup/index.tsx, src/components/ImageUploader.tsx, src/components/myInfo/UserProfile.tsx, src/recoil/currentUser.ts
resolve #149 
- ImageUploader isReset prop 추가
- recoil key에 uuid로 난수 부여
- 내정보 닉네임 이미존재하는 닉네임인지 여부 검사
- 내정보 프로필 수정 모달 isReset으로 이미지 초기화
isReset(boolean) 여부로 ImageBox값이 prop으로 받은 value를 보일지 아니면 새로 받은 값을 보일지 결정
- isReset : true면 value로 받은 기본 이미지가 출력
- isReset: false면 value가 아닌 onChange로 받은 DataURL이 출력
[next js에서 recoil을 쓰면 duplicate key 경고를 만나는 데 uuid 난수를 키에 부여해서 해당 경고 해결](https://vaulted-count-177.notion.site/Duplicate-atom-key-currentUser-This-is-a-FATAL-ERROR-dab311dbe79f45c39425a5b63df101e6)
useQuery의 refetch를 쓸까 했지만 그러면 api를 2번 호출해야 되고 현재 isError, onSuccess, isLoading 같은 useQuery의 값을 사용할 게 아니라서 직접 axiosInstance 호출
1번 사용
=> refactor: 내정보 페이지 보완

pages/signup/index.tsx
유효성 검사 시 다른 input을 작성하면 기존 에러메시지가 사라지는 버그 해결 
이메일 에러 후 비밀번호 에러, 확인 입력, 다시 비밀번호 입력 시 기존의 에러가 여전히 존재하는 것을 확인했습니다.
=> fix: 회원가입 오류 메시지 에러 해결

pages/myInfo/index.tsx, src/utils/localToken.ts
resolve #149 
api 없이 로그아웃 removeLocalToken으로 구현
로그아웃 버튼 클릭 시 removeLocalToken 함수 사용, 그리고 로그인 페이지로 라우팅
=> feat: api 없이 로그아웃 removeLocalToken으로 구현

pages/_app.tsx, pages/user/index.tsx, src/components/Layout/Header.tsx, src/components/Layout/Navigation.tsx, src/components/Layout/index.tsx, styles/globals.css
resolve #148 
- 최종 디자인을 반영, 토큰 유무에 따라 다른 처리를 하도록 수정했습니다. 
현재 로그인 후, 로그아웃 후 메인, 로그인 페이지로 이동합니다. 그래서 이 때를 기점으로 토큰 유무를 판단하도록 코딩했습니다. 
현재 모바일 화면에서 input에 뭔 가를 입력하려 하면 키보드가 뜨고 키보드 위에 nav가 붙어서 답답합니다. 혹시 sticky로 바꾸면 스크롤 하지 않은 상태에선 키보드 아래에 있지 않을까 생각했는데 아닌 거 같아요... 혹시 해결 방안을 아실까요?
이부분에 대해 고민을 많이 해봤는데, 제 결론은 `굳이 처리할 필요가 없다` 였습니다.
[해당 고민에 관한 글](https://vaulted-count-177.notion.site/a31268f8752d456bb60547cf9cadccac)
혹시 다른 의견이시라면 리뷰해주세요 👀
=> refactor: 레이아웃 보완

pages/create-menu/index.tsx, pages/edit-menu/[id].tsx, pages/signup/index.tsx, src/components/FranchiseSelect.tsx, src/components/ImageUploader.tsx, src/components/myInfo/UserProfile.tsx, src/constants/menuConstant.ts, src/hooks/mutations/useSignupMutation.ts
resolve #165 
- 이미지 삭제가 가능하도록 ImageUploader 컴포넌트에서 이미지 삭제 버튼을 구현했습니다. 
- 이미지 삭제 버튼 구현 
- 이미지 삭제 가능 여부에 따라 isDeletable Prop 받음
이미지 삭제 핸들러
```js
const handleDeleteButtonClick = (
e: React.MouseEvent<SVGElement, MouseEvent>
) => {
e.preventDefault() // 버블링 막기 위해 사용
setImage(null)
onChange(null)
}
```
- 현재는 버튼의 사이즈를 고정해놓았는데, 이미지 업로더 컴포넌트가 작아짐에 따라 크기 변경 미디어 쿼리를
사용해야 합니다. 하지만 현재는 수정 / 생성 페이지에서만 사용해서 고정해놓았습니다.
=> feat : 이미지 삭제 버튼 생성

src/components/detail/CommentList.tsx, src/hooks/mutations/useDeleteCommentMutation.ts
resolve #183 
메뉴 상세 페이지 댓글 삭제
댓글 작성자가 댓글을 단 뒤 오른쪽에 있는 Dots를 눌러 모달을 열고, 모달의 삭제 버튼을 누르면 댓글이 삭제되는데 API가 문제가 있는 듯 해서 화면에 바로 반영은 되지 않고 있습니다.
=> feat: 메뉴 상세 페이지 댓글 삭제

src/hooks/queries/useSearchMenuList.ts
이전 PR #191 에서 useSearchMenu 훅 enabled 조건을
`enabled: franchiseId !== undefined` 에서 `enabled: !!franchiseId`로 변경했습니다.
해당 부분이 이전 API로 인한 레거시인줄 착각하고 바꿨는데, 수정후 동작시켜보니 franchiseId가 0일때 전체검색이 동작하기 때문에 기존 조건으로 다시 복구가 필요합니다!
=> hotfix: useSearchMenu 조건 초기화

src/hooks/mutations/useLoginMutation.ts, src/recoil/currentUser.ts, src/utils/checkToken.ts
resolve #189
- 로그인 오타 수정
- checkToken 조건 변경 
- makeCookieEffects 옵션 변경 
- accessToken 만료 시간이 1분 남았을 때 토큰을 재발급하도록 변경 
- refreshToken 만료시간이 1분 남았을 땐 자동로그아웃 
서버 처리시간이 차이가 나기 때문, 만료시간이 1시 10분이 토큰이 있을 때, 1:09분에 요청을 보내면 재발급 없이 기존 토큰을 사용한다. 그런데 해당 토큰이 서버에선 1:10분에 도착, 에러가 날 수 있어서 여유 시간 1분을 줬다. 
- 아래 링크에선 30초를 줬는데 전 좀 더 줬습니다. 
[참고 링크](https://han-um.tistory.com/17)
기존 코드에선 currentUser의 값이 변경될 때 옵션이 기본값이라 세션 쿠키로 바뀌는 버그가 있었음. 자동 로그인 유지를 위해 옵션에 accessToken의 expirationDate만큼 expires를 줌
=> fix: 로그인 오타 수정 및 토큰 쿠키 관련 조건 변경

src/hooks/queries/useSearchMenuList.ts, src/hooks/queries/useSearchMyMenuList.ts
InfiniteQuery의 isLast 조건으로 마지막 페이지인지 아닌지를 판단하는 조건 수정
현재 마지막페이지 조건이 잘못 입력되어서 마지막 페이지에서 무한으로 api를 쏘는 버그가 있어서 급히 수정했습니다!
확인하신 순서대로 approve해주시면 감사하겠습니다!
=> fix: InfintieQuery isLast 조건 수정

middleware.ts, src/components/ImageUploader.tsx
- 기존에 미들웨어에서 redirect 조건이 문자열 일치여서 완전 일치하지 않는 url(예를 들어 /user/:id) 일때는 걸러주지 못하는 문제를 발견했습니다.
- 또한 signup의 로직이 로그인 시 접근 불가인데 반대로 설정했습니다. 
따라서 미들웨어의 config 기능등을 사용해서 기존의 redirect 문제들과, signup 로직을 수정했습니다. 
변수 사용이 안되어서 config에 url들을 문자열로 적었습니다.
config 에 있는 것만 middleware를 거칩니다. 
```js
export const config = {
matcher: [
'/create-menu',
'/edit-menu/:path*',
'/myInfo/:path*',
'/user/:path*',
'/signup'
]
}
```
=> fix: 미들웨어 redirect 문제 수정

pages/_app.tsx, pages/detail/[id].tsx
resolve #162
메뉴 상세 페이지에 SSR을 적용
- 메뉴 정보를 불러오는 데에 서버 사이드 렌더링을 적용했습니다.
- 댓글은 기존의 CSR 방식으로 불러오는데 후에 필요하다면 적용은 어렵지 않을 것으로 생각됩니다.
움짤로 올리고 싶었으나 아래 링크를 누르면 녹화된 영상이 다운로드가 됩니다. 궁금하시면 눌러서 확인해보시면 좋을 것 같습니다.
https://user-images.githubusercontent.com/81501723/184471893-e4ae2d58-bf26-46b1-acd5-8b1c42820e0c.mov
https://user-images.githubusercontent.com/81501723/184471899-340f946b-794b-4318-98c1-ad17b6b6d4a3.mov
=> feat: 상세 페이지 SSR 적용

src/components/detail/CommentInput.tsx, src/components/detail/MenuDetail.tsx, src/interfaces/index.ts
메뉴 상세 페이지
- Menu interface에 `isLiked` 필드 추가
- 하트의 색 초기값으로 사용
- 로그인 여부 판별 state 수정(currentUser의 id를 통해 비교)
=> feat: 좋아요 여부 판단, 로그인 여부 판별 state 수정

pages/search/index.tsx, pages/user/[id].tsx, src/components/FranchiseInfoList.tsx, src/components/Layout/Header.tsx, src/constants/theme.ts
- 헤더, 네비 height 줄이기
- 헤더가 줄어든 만큼 카테고리, 메뉴판 fixed 요소들 top 수정 
- 헤더의 token 값 SSR로 처리하도록 수정
- 헤더, 네비 height 줄이기 : 6.4rem
- 카테고리, 메뉴판 fixed 요소들:  top:6.4rem
- 헤더의 token 값 SSR로 처리하도록 수정
새로고침 시 쿠키가 있어도 없다고 인식하는 문제가 있었는데 헤더를 렌더링할 때 getServerSideProp에서 token을 넘겨받는 식으로 해결했습니다. 
[ 자세한 내용 ](https://vaulted-count-177.notion.site/getToken-cbc769091ab1442e8599c05b60031ed8)
=> refactor: 레이아웃 최종 디자인 반영 및 토큰 SSR로 받도록 수정

middleware.ts, pages/create-menu/index.tsx, pages/edit-menu/[id].tsx
resolve #216
느린 3g환경에서 로딩이 끝났을 때에도 잠깐 생성 / 수정 페이지가 보이는데, 이때 클릭을 하면 여러번 api가 불러와집니다.
state를 둬서 한번만 누룰 수 있도록 만들었습니다.
=> fix / 수정 / 생성 시 버튼 한번만 누르게 처리

pages/create-menu/index.tsx, pages/edit-menu/[id].tsx, src/hooks/useRouterLoading.ts
- 라우팅 시 로딩을 처리하기 위해 현재 라우팅 중인지 아닌지를 반환하는  hook을 만들었습니다. 
```js
function useRouterLoading() {
const router = useRouter()
const [isRouterChange, setIsRouterChange] = useState(false)
const handleRouteChangeStart = useCallback(() => {
setIsRouterChange((isChange) => !isChange)
}, [])
useEffect(() => {
router.events.on('routeChangeStart', handleRouteChangeStart)
return () => {
router.events.off('routeChangeStart', handleRouteChangeStart)
}
}, [handleRouteChangeStart, router.events])
return isRouterChange
}
export default useRouterLoading
```
사용하는 쪽에서는 boolean 값을 반환받아 스피너 컴포넌트와 함께 조건문으로 사용하실 수 있습니다.
```js
const isRouterLoading = useRouterLoading()
return ( ... 
{isRouterLoading ? <Spinner /> : ''} 
... )
```
현재 create page, edit page에 훅을 적용시켜서 다른 페이지로 이동할 때 로딩 처리가 보여집니다. 
로딩 시 뜨는데, 빠른 네트워크 …
=> feat: 라우팅 로딩 처리를 위한 useRouterChangeHook 생성
